/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as ReceptionistRouteImport } from './routes/receptionist'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as NurseRouteImport } from './routes/nurse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as ReceptionistIndexRouteImport } from './routes/receptionist.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as NurseIndexRouteImport } from './routes/nurse.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as SuperAdminStaffRouteImport } from './routes/super-admin.staff'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminReportsRouteImport } from './routes/super-admin.reports'
import { Route as SuperAdminProfileRouteImport } from './routes/super-admin.profile'
import { Route as SuperAdminNotificationsRouteImport } from './routes/super-admin.notifications'
import { Route as SuperAdminHospitalsRouteImport } from './routes/super-admin.hospitals'
import { Route as SuperAdminDoctorsRouteImport } from './routes/super-admin.doctors'
import { Route as SuperAdminAnalyticsRouteImport } from './routes/super-admin.analytics'
import { Route as ReceptionistSettingsRouteImport } from './routes/receptionist.settings'
import { Route as ReceptionistScheduleRouteImport } from './routes/receptionist.schedule'
import { Route as ReceptionistRegisterRouteImport } from './routes/receptionist.register'
import { Route as ReceptionistQueueRouteImport } from './routes/receptionist.queue'
import { Route as ReceptionistProfileRouteImport } from './routes/receptionist.profile'
import { Route as ReceptionistPatientsRouteImport } from './routes/receptionist.patients'
import { Route as ReceptionistNotificationsRouteImport } from './routes/receptionist.notifications'
import { Route as ReceptionistDoctorsRouteImport } from './routes/receptionist.doctors'
import { Route as ReceptionistBillingRouteImport } from './routes/receptionist.billing'
import { Route as ReceptionistAppointmentsRouteImport } from './routes/receptionist.appointments'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientScheduleRouteImport } from './routes/patient.schedule'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientPrescriptionsRouteImport } from './routes/patient.prescriptions'
import { Route as PatientNotificationsRouteImport } from './routes/patient.notifications'
import { Route as PatientDownloadsRouteImport } from './routes/patient.downloads'
import { Route as PatientBillsRouteImport } from './routes/patient.bills'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as NurseVitalsRouteImport } from './routes/nurse.vitals'
import { Route as NurseTasksRouteImport } from './routes/nurse.tasks'
import { Route as NurseSettingsRouteImport } from './routes/nurse.settings'
import { Route as NurseScheduleRouteImport } from './routes/nurse.schedule'
import { Route as NurseProfileRouteImport } from './routes/nurse.profile'
import { Route as NursePatientsRouteImport } from './routes/nurse.patients'
import { Route as NurseNotificationsRouteImport } from './routes/nurse.notifications'
import { Route as NurseMedicationsRouteImport } from './routes/nurse.medications'
import { Route as NurseInjectionsRouteImport } from './routes/nurse.injections'
import { Route as NurseBedsRouteImport } from './routes/nurse.beds'
import { Route as DoctorSettingsRouteImport } from './routes/doctor.settings'
import { Route as DoctorScheduleRouteImport } from './routes/doctor.schedule'
import { Route as DoctorReportsRouteImport } from './routes/doctor.reports'
import { Route as DoctorProfileRouteImport } from './routes/doctor.profile'
import { Route as DoctorPrescriptionsRouteImport } from './routes/doctor.prescriptions'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorNotificationsRouteImport } from './routes/doctor.notifications'
import { Route as DoctorLeaveRouteImport } from './routes/doctor.leave'
import { Route as DoctorAppointmentsRouteImport } from './routes/doctor.appointments'
import { Route as DoctorPatientsIndexRouteImport } from './routes/doctor.patients.index'
import { Route as DoctorPatientsIdRouteImport } from './routes/doctor.patients.$id'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionistRoute = ReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseRoute = NurseRouteImport.update({
  id: '/nurse',
  path: '/nurse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ReceptionistIndexRoute = ReceptionistIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceptionistRoute,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const NurseIndexRoute = NurseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const SuperAdminStaffRoute = SuperAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminReportsRoute = SuperAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminProfileRoute = SuperAdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminNotificationsRoute = SuperAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminHospitalsRoute = SuperAdminHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminDoctorsRoute = SuperAdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminAnalyticsRoute = SuperAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ReceptionistSettingsRoute = ReceptionistSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistScheduleRoute = ReceptionistScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistRegisterRoute = ReceptionistRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistQueueRoute = ReceptionistQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistProfileRoute = ReceptionistProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistPatientsRoute = ReceptionistPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistNotificationsRoute =
  ReceptionistNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const ReceptionistDoctorsRoute = ReceptionistDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistBillingRoute = ReceptionistBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => ReceptionistRoute,
} as any)
const ReceptionistAppointmentsRoute =
  ReceptionistAppointmentsRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => ReceptionistRoute,
  } as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientScheduleRoute = PatientScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientPrescriptionsRoute = PatientPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PatientRoute,
} as any)
const PatientNotificationsRoute = PatientNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PatientRoute,
} as any)
const PatientDownloadsRoute = PatientDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => PatientRoute,
} as any)
const PatientBillsRoute = PatientBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const NurseVitalsRoute = NurseVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => NurseRoute,
} as any)
const NurseTasksRoute = NurseTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => NurseRoute,
} as any)
const NurseSettingsRoute = NurseSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NurseRoute,
} as any)
const NurseScheduleRoute = NurseScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => NurseRoute,
} as any)
const NurseProfileRoute = NurseProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => NurseRoute,
} as any)
const NursePatientsRoute = NursePatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => NurseRoute,
} as any)
const NurseNotificationsRoute = NurseNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => NurseRoute,
} as any)
const NurseMedicationsRoute = NurseMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => NurseRoute,
} as any)
const NurseInjectionsRoute = NurseInjectionsRouteImport.update({
  id: '/injections',
  path: '/injections',
  getParentRoute: () => NurseRoute,
} as any)
const NurseBedsRoute = NurseBedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => NurseRoute,
} as any)
const DoctorSettingsRoute = DoctorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorScheduleRoute = DoctorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorReportsRoute = DoctorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorProfileRoute = DoctorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPrescriptionsRoute = DoctorPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorNotificationsRoute = DoctorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorLeaveRoute = DoctorLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAppointmentsRoute = DoctorAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorPatientsIndexRoute = DoctorPatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorPatientsRoute,
} as any)
const DoctorPatientsIdRoute = DoctorPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DoctorPatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/receptionist': typeof ReceptionistRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/leave': typeof DoctorLeaveRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/nurse/beds': typeof NurseBedsRoute
  '/nurse/injections': typeof NurseInjectionsRoute
  '/nurse/medications': typeof NurseMedicationsRoute
  '/nurse/notifications': typeof NurseNotificationsRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/profile': typeof NurseProfileRoute
  '/nurse/schedule': typeof NurseScheduleRoute
  '/nurse/settings': typeof NurseSettingsRoute
  '/nurse/tasks': typeof NurseTasksRoute
  '/nurse/vitals': typeof NurseVitalsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/bills': typeof PatientBillsRoute
  '/patient/downloads': typeof PatientDownloadsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/schedule': typeof PatientScheduleRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/billing': typeof ReceptionistBillingRoute
  '/receptionist/doctors': typeof ReceptionistDoctorsRoute
  '/receptionist/notifications': typeof ReceptionistNotificationsRoute
  '/receptionist/patients': typeof ReceptionistPatientsRoute
  '/receptionist/profile': typeof ReceptionistProfileRoute
  '/receptionist/queue': typeof ReceptionistQueueRoute
  '/receptionist/register': typeof ReceptionistRegisterRoute
  '/receptionist/schedule': typeof ReceptionistScheduleRoute
  '/receptionist/settings': typeof ReceptionistSettingsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/doctors': typeof SuperAdminDoctorsRoute
  '/super-admin/hospitals': typeof SuperAdminHospitalsRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/staff': typeof SuperAdminStaffRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/leave': typeof DoctorLeaveRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/nurse/beds': typeof NurseBedsRoute
  '/nurse/injections': typeof NurseInjectionsRoute
  '/nurse/medications': typeof NurseMedicationsRoute
  '/nurse/notifications': typeof NurseNotificationsRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/profile': typeof NurseProfileRoute
  '/nurse/schedule': typeof NurseScheduleRoute
  '/nurse/settings': typeof NurseSettingsRoute
  '/nurse/tasks': typeof NurseTasksRoute
  '/nurse/vitals': typeof NurseVitalsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/bills': typeof PatientBillsRoute
  '/patient/downloads': typeof PatientDownloadsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/schedule': typeof PatientScheduleRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/billing': typeof ReceptionistBillingRoute
  '/receptionist/doctors': typeof ReceptionistDoctorsRoute
  '/receptionist/notifications': typeof ReceptionistNotificationsRoute
  '/receptionist/patients': typeof ReceptionistPatientsRoute
  '/receptionist/profile': typeof ReceptionistProfileRoute
  '/receptionist/queue': typeof ReceptionistQueueRoute
  '/receptionist/register': typeof ReceptionistRegisterRoute
  '/receptionist/schedule': typeof ReceptionistScheduleRoute
  '/receptionist/settings': typeof ReceptionistSettingsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/doctors': typeof SuperAdminDoctorsRoute
  '/super-admin/hospitals': typeof SuperAdminHospitalsRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/staff': typeof SuperAdminStaffRoute
  '/doctor': typeof DoctorIndexRoute
  '/nurse': typeof NurseIndexRoute
  '/patient': typeof PatientIndexRoute
  '/receptionist': typeof ReceptionistIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/patients': typeof DoctorPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nurse': typeof NurseRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/receptionist': typeof ReceptionistRouteWithChildren
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/doctor/appointments': typeof DoctorAppointmentsRoute
  '/doctor/leave': typeof DoctorLeaveRoute
  '/doctor/notifications': typeof DoctorNotificationsRoute
  '/doctor/patients': typeof DoctorPatientsRouteWithChildren
  '/doctor/prescriptions': typeof DoctorPrescriptionsRoute
  '/doctor/profile': typeof DoctorProfileRoute
  '/doctor/reports': typeof DoctorReportsRoute
  '/doctor/schedule': typeof DoctorScheduleRoute
  '/doctor/settings': typeof DoctorSettingsRoute
  '/nurse/beds': typeof NurseBedsRoute
  '/nurse/injections': typeof NurseInjectionsRoute
  '/nurse/medications': typeof NurseMedicationsRoute
  '/nurse/notifications': typeof NurseNotificationsRoute
  '/nurse/patients': typeof NursePatientsRoute
  '/nurse/profile': typeof NurseProfileRoute
  '/nurse/schedule': typeof NurseScheduleRoute
  '/nurse/settings': typeof NurseSettingsRoute
  '/nurse/tasks': typeof NurseTasksRoute
  '/nurse/vitals': typeof NurseVitalsRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/bills': typeof PatientBillsRoute
  '/patient/downloads': typeof PatientDownloadsRoute
  '/patient/notifications': typeof PatientNotificationsRoute
  '/patient/prescriptions': typeof PatientPrescriptionsRoute
  '/patient/profile': typeof PatientProfileRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/schedule': typeof PatientScheduleRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/receptionist/appointments': typeof ReceptionistAppointmentsRoute
  '/receptionist/billing': typeof ReceptionistBillingRoute
  '/receptionist/doctors': typeof ReceptionistDoctorsRoute
  '/receptionist/notifications': typeof ReceptionistNotificationsRoute
  '/receptionist/patients': typeof ReceptionistPatientsRoute
  '/receptionist/profile': typeof ReceptionistProfileRoute
  '/receptionist/queue': typeof ReceptionistQueueRoute
  '/receptionist/register': typeof ReceptionistRegisterRoute
  '/receptionist/schedule': typeof ReceptionistScheduleRoute
  '/receptionist/settings': typeof ReceptionistSettingsRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/doctors': typeof SuperAdminDoctorsRoute
  '/super-admin/hospitals': typeof SuperAdminHospitalsRoute
  '/super-admin/notifications': typeof SuperAdminNotificationsRoute
  '/super-admin/profile': typeof SuperAdminProfileRoute
  '/super-admin/reports': typeof SuperAdminReportsRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/staff': typeof SuperAdminStaffRoute
  '/doctor/': typeof DoctorIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/receptionist/': typeof ReceptionistIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/doctor/patients/$id': typeof DoctorPatientsIdRoute
  '/doctor/patients/': typeof DoctorPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/receptionist'
    | '/super-admin'
    | '/doctor/appointments'
    | '/doctor/leave'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/nurse/beds'
    | '/nurse/injections'
    | '/nurse/medications'
    | '/nurse/notifications'
    | '/nurse/patients'
    | '/nurse/profile'
    | '/nurse/schedule'
    | '/nurse/settings'
    | '/nurse/tasks'
    | '/nurse/vitals'
    | '/patient/appointments'
    | '/patient/bills'
    | '/patient/downloads'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/schedule'
    | '/patient/settings'
    | '/receptionist/appointments'
    | '/receptionist/billing'
    | '/receptionist/doctors'
    | '/receptionist/notifications'
    | '/receptionist/patients'
    | '/receptionist/profile'
    | '/receptionist/queue'
    | '/receptionist/register'
    | '/receptionist/schedule'
    | '/receptionist/settings'
    | '/super-admin/analytics'
    | '/super-admin/doctors'
    | '/super-admin/hospitals'
    | '/super-admin/notifications'
    | '/super-admin/profile'
    | '/super-admin/reports'
    | '/super-admin/settings'
    | '/super-admin/staff'
    | '/doctor/'
    | '/nurse/'
    | '/patient/'
    | '/receptionist/'
    | '/super-admin/'
    | '/doctor/patients/$id'
    | '/doctor/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/doctor/appointments'
    | '/doctor/leave'
    | '/doctor/notifications'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/nurse/beds'
    | '/nurse/injections'
    | '/nurse/medications'
    | '/nurse/notifications'
    | '/nurse/patients'
    | '/nurse/profile'
    | '/nurse/schedule'
    | '/nurse/settings'
    | '/nurse/tasks'
    | '/nurse/vitals'
    | '/patient/appointments'
    | '/patient/bills'
    | '/patient/downloads'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/schedule'
    | '/patient/settings'
    | '/receptionist/appointments'
    | '/receptionist/billing'
    | '/receptionist/doctors'
    | '/receptionist/notifications'
    | '/receptionist/patients'
    | '/receptionist/profile'
    | '/receptionist/queue'
    | '/receptionist/register'
    | '/receptionist/schedule'
    | '/receptionist/settings'
    | '/super-admin/analytics'
    | '/super-admin/doctors'
    | '/super-admin/hospitals'
    | '/super-admin/notifications'
    | '/super-admin/profile'
    | '/super-admin/reports'
    | '/super-admin/settings'
    | '/super-admin/staff'
    | '/doctor'
    | '/nurse'
    | '/patient'
    | '/receptionist'
    | '/super-admin'
    | '/doctor/patients/$id'
    | '/doctor/patients'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/forgot-password'
    | '/login'
    | '/nurse'
    | '/patient'
    | '/receptionist'
    | '/super-admin'
    | '/doctor/appointments'
    | '/doctor/leave'
    | '/doctor/notifications'
    | '/doctor/patients'
    | '/doctor/prescriptions'
    | '/doctor/profile'
    | '/doctor/reports'
    | '/doctor/schedule'
    | '/doctor/settings'
    | '/nurse/beds'
    | '/nurse/injections'
    | '/nurse/medications'
    | '/nurse/notifications'
    | '/nurse/patients'
    | '/nurse/profile'
    | '/nurse/schedule'
    | '/nurse/settings'
    | '/nurse/tasks'
    | '/nurse/vitals'
    | '/patient/appointments'
    | '/patient/bills'
    | '/patient/downloads'
    | '/patient/notifications'
    | '/patient/prescriptions'
    | '/patient/profile'
    | '/patient/reports'
    | '/patient/schedule'
    | '/patient/settings'
    | '/receptionist/appointments'
    | '/receptionist/billing'
    | '/receptionist/doctors'
    | '/receptionist/notifications'
    | '/receptionist/patients'
    | '/receptionist/profile'
    | '/receptionist/queue'
    | '/receptionist/register'
    | '/receptionist/schedule'
    | '/receptionist/settings'
    | '/super-admin/analytics'
    | '/super-admin/doctors'
    | '/super-admin/hospitals'
    | '/super-admin/notifications'
    | '/super-admin/profile'
    | '/super-admin/reports'
    | '/super-admin/settings'
    | '/super-admin/staff'
    | '/doctor/'
    | '/nurse/'
    | '/patient/'
    | '/receptionist/'
    | '/super-admin/'
    | '/doctor/patients/$id'
    | '/doctor/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NurseRoute: typeof NurseRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  ReceptionistRoute: typeof ReceptionistRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receptionist': {
      id: '/receptionist'
      path: '/receptionist'
      fullPath: '/receptionist'
      preLoaderRoute: typeof ReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse': {
      id: '/nurse'
      path: '/nurse'
      fullPath: '/nurse'
      preLoaderRoute: typeof NurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/receptionist/': {
      id: '/receptionist/'
      path: '/'
      fullPath: '/receptionist/'
      preLoaderRoute: typeof ReceptionistIndexRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/nurse/': {
      id: '/nurse/'
      path: '/'
      fullPath: '/nurse/'
      preLoaderRoute: typeof NurseIndexRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/super-admin/staff': {
      id: '/super-admin/staff'
      path: '/staff'
      fullPath: '/super-admin/staff'
      preLoaderRoute: typeof SuperAdminStaffRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/reports': {
      id: '/super-admin/reports'
      path: '/reports'
      fullPath: '/super-admin/reports'
      preLoaderRoute: typeof SuperAdminReportsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/profile': {
      id: '/super-admin/profile'
      path: '/profile'
      fullPath: '/super-admin/profile'
      preLoaderRoute: typeof SuperAdminProfileRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/notifications': {
      id: '/super-admin/notifications'
      path: '/notifications'
      fullPath: '/super-admin/notifications'
      preLoaderRoute: typeof SuperAdminNotificationsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/hospitals': {
      id: '/super-admin/hospitals'
      path: '/hospitals'
      fullPath: '/super-admin/hospitals'
      preLoaderRoute: typeof SuperAdminHospitalsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/doctors': {
      id: '/super-admin/doctors'
      path: '/doctors'
      fullPath: '/super-admin/doctors'
      preLoaderRoute: typeof SuperAdminDoctorsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/analytics': {
      id: '/super-admin/analytics'
      path: '/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperAdminAnalyticsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/receptionist/settings': {
      id: '/receptionist/settings'
      path: '/settings'
      fullPath: '/receptionist/settings'
      preLoaderRoute: typeof ReceptionistSettingsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/schedule': {
      id: '/receptionist/schedule'
      path: '/schedule'
      fullPath: '/receptionist/schedule'
      preLoaderRoute: typeof ReceptionistScheduleRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/register': {
      id: '/receptionist/register'
      path: '/register'
      fullPath: '/receptionist/register'
      preLoaderRoute: typeof ReceptionistRegisterRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/queue': {
      id: '/receptionist/queue'
      path: '/queue'
      fullPath: '/receptionist/queue'
      preLoaderRoute: typeof ReceptionistQueueRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/profile': {
      id: '/receptionist/profile'
      path: '/profile'
      fullPath: '/receptionist/profile'
      preLoaderRoute: typeof ReceptionistProfileRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/patients': {
      id: '/receptionist/patients'
      path: '/patients'
      fullPath: '/receptionist/patients'
      preLoaderRoute: typeof ReceptionistPatientsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/notifications': {
      id: '/receptionist/notifications'
      path: '/notifications'
      fullPath: '/receptionist/notifications'
      preLoaderRoute: typeof ReceptionistNotificationsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/doctors': {
      id: '/receptionist/doctors'
      path: '/doctors'
      fullPath: '/receptionist/doctors'
      preLoaderRoute: typeof ReceptionistDoctorsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/billing': {
      id: '/receptionist/billing'
      path: '/billing'
      fullPath: '/receptionist/billing'
      preLoaderRoute: typeof ReceptionistBillingRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/receptionist/appointments': {
      id: '/receptionist/appointments'
      path: '/appointments'
      fullPath: '/receptionist/appointments'
      preLoaderRoute: typeof ReceptionistAppointmentsRouteImport
      parentRoute: typeof ReceptionistRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/schedule': {
      id: '/patient/schedule'
      path: '/schedule'
      fullPath: '/patient/schedule'
      preLoaderRoute: typeof PatientScheduleRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/prescriptions': {
      id: '/patient/prescriptions'
      path: '/prescriptions'
      fullPath: '/patient/prescriptions'
      preLoaderRoute: typeof PatientPrescriptionsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/notifications': {
      id: '/patient/notifications'
      path: '/notifications'
      fullPath: '/patient/notifications'
      preLoaderRoute: typeof PatientNotificationsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/downloads': {
      id: '/patient/downloads'
      path: '/downloads'
      fullPath: '/patient/downloads'
      preLoaderRoute: typeof PatientDownloadsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/bills': {
      id: '/patient/bills'
      path: '/bills'
      fullPath: '/patient/bills'
      preLoaderRoute: typeof PatientBillsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/nurse/vitals': {
      id: '/nurse/vitals'
      path: '/vitals'
      fullPath: '/nurse/vitals'
      preLoaderRoute: typeof NurseVitalsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/tasks': {
      id: '/nurse/tasks'
      path: '/tasks'
      fullPath: '/nurse/tasks'
      preLoaderRoute: typeof NurseTasksRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/settings': {
      id: '/nurse/settings'
      path: '/settings'
      fullPath: '/nurse/settings'
      preLoaderRoute: typeof NurseSettingsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/schedule': {
      id: '/nurse/schedule'
      path: '/schedule'
      fullPath: '/nurse/schedule'
      preLoaderRoute: typeof NurseScheduleRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/profile': {
      id: '/nurse/profile'
      path: '/profile'
      fullPath: '/nurse/profile'
      preLoaderRoute: typeof NurseProfileRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/patients': {
      id: '/nurse/patients'
      path: '/patients'
      fullPath: '/nurse/patients'
      preLoaderRoute: typeof NursePatientsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/notifications': {
      id: '/nurse/notifications'
      path: '/notifications'
      fullPath: '/nurse/notifications'
      preLoaderRoute: typeof NurseNotificationsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/medications': {
      id: '/nurse/medications'
      path: '/medications'
      fullPath: '/nurse/medications'
      preLoaderRoute: typeof NurseMedicationsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/injections': {
      id: '/nurse/injections'
      path: '/injections'
      fullPath: '/nurse/injections'
      preLoaderRoute: typeof NurseInjectionsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/nurse/beds': {
      id: '/nurse/beds'
      path: '/beds'
      fullPath: '/nurse/beds'
      preLoaderRoute: typeof NurseBedsRouteImport
      parentRoute: typeof NurseRoute
    }
    '/doctor/settings': {
      id: '/doctor/settings'
      path: '/settings'
      fullPath: '/doctor/settings'
      preLoaderRoute: typeof DoctorSettingsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/schedule': {
      id: '/doctor/schedule'
      path: '/schedule'
      fullPath: '/doctor/schedule'
      preLoaderRoute: typeof DoctorScheduleRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/reports': {
      id: '/doctor/reports'
      path: '/reports'
      fullPath: '/doctor/reports'
      preLoaderRoute: typeof DoctorReportsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/profile': {
      id: '/doctor/profile'
      path: '/profile'
      fullPath: '/doctor/profile'
      preLoaderRoute: typeof DoctorProfileRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/prescriptions': {
      id: '/doctor/prescriptions'
      path: '/prescriptions'
      fullPath: '/doctor/prescriptions'
      preLoaderRoute: typeof DoctorPrescriptionsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/notifications': {
      id: '/doctor/notifications'
      path: '/notifications'
      fullPath: '/doctor/notifications'
      preLoaderRoute: typeof DoctorNotificationsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/leave': {
      id: '/doctor/leave'
      path: '/leave'
      fullPath: '/doctor/leave'
      preLoaderRoute: typeof DoctorLeaveRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/appointments': {
      id: '/doctor/appointments'
      path: '/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof DoctorAppointmentsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/patients/': {
      id: '/doctor/patients/'
      path: '/'
      fullPath: '/doctor/patients/'
      preLoaderRoute: typeof DoctorPatientsIndexRouteImport
      parentRoute: typeof DoctorPatientsRoute
    }
    '/doctor/patients/$id': {
      id: '/doctor/patients/$id'
      path: '/$id'
      fullPath: '/doctor/patients/$id'
      preLoaderRoute: typeof DoctorPatientsIdRouteImport
      parentRoute: typeof DoctorPatientsRoute
    }
  }
}

interface DoctorPatientsRouteChildren {
  DoctorPatientsIdRoute: typeof DoctorPatientsIdRoute
  DoctorPatientsIndexRoute: typeof DoctorPatientsIndexRoute
}

const DoctorPatientsRouteChildren: DoctorPatientsRouteChildren = {
  DoctorPatientsIdRoute: DoctorPatientsIdRoute,
  DoctorPatientsIndexRoute: DoctorPatientsIndexRoute,
}

const DoctorPatientsRouteWithChildren = DoctorPatientsRoute._addFileChildren(
  DoctorPatientsRouteChildren,
)

interface DoctorRouteChildren {
  DoctorAppointmentsRoute: typeof DoctorAppointmentsRoute
  DoctorLeaveRoute: typeof DoctorLeaveRoute
  DoctorNotificationsRoute: typeof DoctorNotificationsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRouteWithChildren
  DoctorPrescriptionsRoute: typeof DoctorPrescriptionsRoute
  DoctorProfileRoute: typeof DoctorProfileRoute
  DoctorReportsRoute: typeof DoctorReportsRoute
  DoctorScheduleRoute: typeof DoctorScheduleRoute
  DoctorSettingsRoute: typeof DoctorSettingsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAppointmentsRoute: DoctorAppointmentsRoute,
  DoctorLeaveRoute: DoctorLeaveRoute,
  DoctorNotificationsRoute: DoctorNotificationsRoute,
  DoctorPatientsRoute: DoctorPatientsRouteWithChildren,
  DoctorPrescriptionsRoute: DoctorPrescriptionsRoute,
  DoctorProfileRoute: DoctorProfileRoute,
  DoctorReportsRoute: DoctorReportsRoute,
  DoctorScheduleRoute: DoctorScheduleRoute,
  DoctorSettingsRoute: DoctorSettingsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface NurseRouteChildren {
  NurseBedsRoute: typeof NurseBedsRoute
  NurseInjectionsRoute: typeof NurseInjectionsRoute
  NurseMedicationsRoute: typeof NurseMedicationsRoute
  NurseNotificationsRoute: typeof NurseNotificationsRoute
  NursePatientsRoute: typeof NursePatientsRoute
  NurseProfileRoute: typeof NurseProfileRoute
  NurseScheduleRoute: typeof NurseScheduleRoute
  NurseSettingsRoute: typeof NurseSettingsRoute
  NurseTasksRoute: typeof NurseTasksRoute
  NurseVitalsRoute: typeof NurseVitalsRoute
  NurseIndexRoute: typeof NurseIndexRoute
}

const NurseRouteChildren: NurseRouteChildren = {
  NurseBedsRoute: NurseBedsRoute,
  NurseInjectionsRoute: NurseInjectionsRoute,
  NurseMedicationsRoute: NurseMedicationsRoute,
  NurseNotificationsRoute: NurseNotificationsRoute,
  NursePatientsRoute: NursePatientsRoute,
  NurseProfileRoute: NurseProfileRoute,
  NurseScheduleRoute: NurseScheduleRoute,
  NurseSettingsRoute: NurseSettingsRoute,
  NurseTasksRoute: NurseTasksRoute,
  NurseVitalsRoute: NurseVitalsRoute,
  NurseIndexRoute: NurseIndexRoute,
}

const NurseRouteWithChildren = NurseRoute._addFileChildren(NurseRouteChildren)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientBillsRoute: typeof PatientBillsRoute
  PatientDownloadsRoute: typeof PatientDownloadsRoute
  PatientNotificationsRoute: typeof PatientNotificationsRoute
  PatientPrescriptionsRoute: typeof PatientPrescriptionsRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientScheduleRoute: typeof PatientScheduleRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientBillsRoute: PatientBillsRoute,
  PatientDownloadsRoute: PatientDownloadsRoute,
  PatientNotificationsRoute: PatientNotificationsRoute,
  PatientPrescriptionsRoute: PatientPrescriptionsRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientScheduleRoute: PatientScheduleRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface ReceptionistRouteChildren {
  ReceptionistAppointmentsRoute: typeof ReceptionistAppointmentsRoute
  ReceptionistBillingRoute: typeof ReceptionistBillingRoute
  ReceptionistDoctorsRoute: typeof ReceptionistDoctorsRoute
  ReceptionistNotificationsRoute: typeof ReceptionistNotificationsRoute
  ReceptionistPatientsRoute: typeof ReceptionistPatientsRoute
  ReceptionistProfileRoute: typeof ReceptionistProfileRoute
  ReceptionistQueueRoute: typeof ReceptionistQueueRoute
  ReceptionistRegisterRoute: typeof ReceptionistRegisterRoute
  ReceptionistScheduleRoute: typeof ReceptionistScheduleRoute
  ReceptionistSettingsRoute: typeof ReceptionistSettingsRoute
  ReceptionistIndexRoute: typeof ReceptionistIndexRoute
}

const ReceptionistRouteChildren: ReceptionistRouteChildren = {
  ReceptionistAppointmentsRoute: ReceptionistAppointmentsRoute,
  ReceptionistBillingRoute: ReceptionistBillingRoute,
  ReceptionistDoctorsRoute: ReceptionistDoctorsRoute,
  ReceptionistNotificationsRoute: ReceptionistNotificationsRoute,
  ReceptionistPatientsRoute: ReceptionistPatientsRoute,
  ReceptionistProfileRoute: ReceptionistProfileRoute,
  ReceptionistQueueRoute: ReceptionistQueueRoute,
  ReceptionistRegisterRoute: ReceptionistRegisterRoute,
  ReceptionistScheduleRoute: ReceptionistScheduleRoute,
  ReceptionistSettingsRoute: ReceptionistSettingsRoute,
  ReceptionistIndexRoute: ReceptionistIndexRoute,
}

const ReceptionistRouteWithChildren = ReceptionistRoute._addFileChildren(
  ReceptionistRouteChildren,
)

interface SuperAdminRouteChildren {
  SuperAdminAnalyticsRoute: typeof SuperAdminAnalyticsRoute
  SuperAdminDoctorsRoute: typeof SuperAdminDoctorsRoute
  SuperAdminHospitalsRoute: typeof SuperAdminHospitalsRoute
  SuperAdminNotificationsRoute: typeof SuperAdminNotificationsRoute
  SuperAdminProfileRoute: typeof SuperAdminProfileRoute
  SuperAdminReportsRoute: typeof SuperAdminReportsRoute
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminStaffRoute: typeof SuperAdminStaffRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminAnalyticsRoute: SuperAdminAnalyticsRoute,
  SuperAdminDoctorsRoute: SuperAdminDoctorsRoute,
  SuperAdminHospitalsRoute: SuperAdminHospitalsRoute,
  SuperAdminNotificationsRoute: SuperAdminNotificationsRoute,
  SuperAdminProfileRoute: SuperAdminProfileRoute,
  SuperAdminReportsRoute: SuperAdminReportsRoute,
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminStaffRoute: SuperAdminStaffRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NurseRoute: NurseRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  ReceptionistRoute: ReceptionistRouteWithChildren,
  SuperAdminRoute: SuperAdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
